services:

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./auth-service/.env.development.local
    networks:
      - microservices-network
    restart: unless-stopped

  # product-service: (uncomment when ready)
  #   build:
  #     context: ./product-service
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - microservices-network

networks:
  microservices-network:
    driver: bridge
